### ISSUE TITLE
java.lang.NoSuchMethodError: graphql.ExecutionInput$Builder.executionId(

### ISSUE THREAD

**Issue by jlauu** [smoketurner/dropwizard-graphql#31]
dropwizard v.0.7.1
graphql-java v.13.0.0
graphql-core v.1.3.12-4

Getting the following error when making a graphql request
```
0:0:0:0:0:0:0:1 -  -  [23/Jul/2019:18:35:51 +0000] "POST /graphql HTTP/1.1" 500 - "-" "insomnia/6.5.4" 23
ERROR [2019-07-23 18:35:51,923] graphql.servlet.AbstractGraphQLHttpServlet: Error executing GraphQL request!
! java.lang.NoSuchMethodError: graphql.ExecutionInput$Builder.executionId(Lgraphql/execution/ExecutionId;)Lgraphql/ExecutionInput$Builder;
! at graphql.servlet.input.GraphQLSingleInvocationInput.createExecutionInput(GraphQLSingleInvocationInput.java:52)
! at graphql.servlet.input.GraphQLSingleInvocationInput.<init>(GraphQLSingleInvocationInput.java:26)
! at graphql.servlet.input.GraphQLInvocationInputFactory.create(GraphQLInvocationInputFactory.java:72)
! at graphql.servlet.input.GraphQLInvocationInputFactory.create(GraphQLInvocationInputFactory.java:40)
! at graphql.servlet.AbstractGraphQLHttpServlet.lambda$init$4(AbstractGraphQLHttpServlet.java:237)
! at graphql.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:342)
! at graphql.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet.java:333)
! at graphql.servlet.AbstractGraphQLHttpServlet.doPost(AbstractGraphQLHttpServlet.java:365)
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

**Comment by jplock** [comment]
Can you upgrade to a newer version of dropwizard? This library is based off of 1.3.12

**Comment by jlauu** [comment]
Turns out I actually built an older version of graphql-java, and it should be `v13.0`

**Comment by harish2296** [comment]
I got the same issue my pom looks like this below can u help me @jlauu ?
<dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphql-spring-boot-starter</artifactId>
			<version>7.0.1</version>
		</dependency>

		<dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphql-java-tools</artifactId>
			<version>5.4.0</version>
		</dependency>
