### ISSUE TITLE
URI is not hierarchical

### ISSUE THREAD

**Issue by mcdore** [smoketurner/dropwizard-graphql#4]
When I run this from inside Eclipse, it starts up fine, but if I run from the command line, I get the error:
`java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at com.smoketurner.dropwizard.graphql.GraphQLFactory.getSchemaFile(GraphQLFactory.java:65)
	at com.smoketurner.dropwizard.graphql.GraphQLFactory.build(GraphQLFactory.java:125)
	at com.smoketurner.dropwizard.graphql.GraphQLBundle.run(GraphQLBundle.java:40)
	at com.smoketurner.dropwizard.graphql.GraphQLBundle.run(GraphQLBundle.java:27)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:93)
	at com.example.helloworld.HelloWorldApplication.main(HelloWorldApplication.java:35)`

It looks like the issue is something related to this:
https://stackoverflow.com/questions/20389255/reading-a-resource-file-from-within-jar

**Comment by phact** [comment]
I'm hitting this same issue. IDEA kept throwing errors until I ran ´mvn package´ and now idea works I get ´URI is not heirarchical´ when I try to run from the jar directly.

**Comment by phact** [comment]
https://github.com/smoketurner/dropwizard-graphql/pull/6

**Comment by apodkutin** [comment]
A small PR regarding this issue https://github.com/smoketurner/dropwizard-graphql/pull/7
